---

sudo: required
dist: bionic

language: python
python:
  - 2.7
  - 3.6
  - 3.7

branches:
  only:
    - develop
    - master

script:
  - make test PYTHONEXE=$(which python)

after_success:
  coveralls
